name: bmi_calculator
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_font_icons: ^2.2.7
  google_fonts: ^6.3.2
  syncfusion_flutter_gauges: ^24.2.9
  url_launcher:
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  flutter_animated_icons: 1.0.1
  animated_icon_button: ^1.0.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
